version: '3'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      TZ: ${POSTGRES_TIMEZONE}
    container_name: jwtauth
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data
